/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "error-container": "#ffdad6",
              "surface-container-high": "#dfe8ff",
              "primary-fixed": "#dae2ff",
              "on-tertiary-container": "#d5ccff",
              "outline-variant": "#c3c6d6",
              "on-error-container": "#93000a",
              "on-primary-fixed": "#001848",
              "secondary-fixed-dim": "#65dca4",
              "background": "#f9f9ff",
              "on-primary": "#ffffff",
              "secondary-container": "#82f9be",
              "on-secondary": "#ffffff",
              "inverse-primary": "#b2c5ff",
              "on-background": "#091c35",
              "outline": "#737685",
              "on-tertiary-fixed": "#1a0063",
              "surface-container-low": "#f0f3ff",
              "on-surface": "#091c35",
              "on-secondary-fixed-variant": "#005235",
              "secondary-fixed": "#82f9be",
              "primary-container": "#0052cc",
              "on-tertiary-fixed-variant": "#4633a0",
              "on-primary-fixed-variant": "#0040a2",
              "tertiary-container": "#5b49b5",
              "on-secondary-container": "#00734c",
              "surface-tint": "#0c56d0",
              "surface-container-lowest": "#ffffff",
              "tertiary": "#432f9c",
              "surface": "#f9f9ff",
              "surface-bright": "#f9f9ff",
              "inverse-surface": "#20314b",
              "error": "#ba1a1a",
              "tertiary-fixed": "#e5deff",
              "primary": "#003d9b",
              "on-tertiary": "#ffffff",
              "surface-variant": "#d6e3ff",
              "secondary": "#006c47",
              "on-surface-variant": "#434654",
              "tertiary-fixed-dim": "#c9bfff",
              "primary-fixed-dim": "#b2c5ff",
              "surface-container-highest": "#d6e3ff",
              "on-primary-container": "#c4d2ff",
              "surface-container": "#e7eeff",
              "surface-dim": "#cadbfc",
              "inverse-on-surface": "#ecf0ff",
              "on-secondary-fixed": "#002113",
              "on-error": "#ffffff"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "spacing": {
              "xl": "32px",
              "xxl": "48px",
              "lg": "24px",
              "sm": "8px",
              "container-max": "1440px",
              "base": "8px",
              "xs": "4px",
              "gutter": "24px",
              "md": "16px"
      },
      "fontFamily": {
              "body-md": ["Inter"],
              "caption": ["Inter"],
              "h3": ["Inter"],
              "h1": ["Inter"],
              "label-md": ["Inter"],
              "h2": ["Inter"],
              "body-lg": ["Inter"],
              "label-sm": ["Inter"]
      },
      "fontSize": {
              "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
              "caption": ["12px", {"lineHeight": "16px", "fontWeight": "400"}],
              "h3": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
              "h1": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "label-md": ["14px", {"lineHeight": "20px", "fontWeight": "600"}],
              "h2": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
              "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
